CREATE TABLE `profiles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `github_url` varchar(255) DEFAULT NULL,
  `avatar_url` varchar(255) DEFAULT NULL,
  `bio` text,
  `location` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `twitter_username` varchar(100) DEFAULT NULL,
  `hireable` tinyint(1) DEFAULT '0',
  `public_repos` int DEFAULT '0',
  `public_gists` int DEFAULT '0',
  `followers` int DEFAULT '0',
  `following` int DEFAULT '0',
  `total_stars` int DEFAULT '0',
  `total_forks` int DEFAULT '0',
  `total_watchers` int DEFAULT '0',
  `avg_stars_per_repo` decimal(10,2) DEFAULT '0.00',
  `most_starred_repo` varchar(255) DEFAULT NULL,
  `most_starred_repo_stars` int DEFAULT '0',
  `recently_active_repos` int DEFAULT '0',
  `original_repos` int DEFAULT '0',
  `forked_repos` int DEFAULT '0',
  `top_languages` json DEFAULT NULL,
  `has_website` tinyint(1) DEFAULT '0',
  `account_age_days` int DEFAULT '0',
  `analyzed_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`),
  KEY `idx_total_stars` (`total_stars`),
  KEY `idx_followers` (`followers`)
);